skip_tags: false
skip_non_tags: true

image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

platform:
  - x86
  - x64

#NPM Doesn't seem to like caching, requires investigation
#cache:
#  - node_modules

init:
  - git config --global core.autocrlf input
  
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019
          platform: x86
    install:
        - ps: Install-Product node 14 x64
        - npm ci
    build_script:
      - npm run make:32
  -
    matrix:
      only:
        - image: Visual Studio 2019
          platform: x64
    install:
        - ps: Install-Product node 14 x64
        - npm ci
    build_script:
      - npm run make
  -
    matrix:
      only:
        - image: Ubuntu
          platform: x86
    install:
      - nvm install 14
      - npm ci
      - sudo apt-get install dpkg fakeroot -y
    build_script:
      - npm run make:32
  -
    matrix:
      only:
        - image: Ubuntu
          platform: x64
    install:
      - nvm install 14
      - npm ci
      - sudo apt-get install dpkg fakeroot -y
    build_script:
      - npm run make
#Disabled since electron-packager doesn't (yet) support darwin/ia32
  -
    matrix:
      only:
        - image: macOS
          platform: x86
#    install:
#      - nvm install 14
#      - npm ci
#    build_script:
#      - npm run make:32
  -
    matrix:
      only:
        - image: macOS
          platform: x64
    install:
      - nvm install 14
      - npm ci
    build_script:
      - npm run make

test: false

artifacts:
  - path: out/make/**/*

deploy:
  tag: Version
  description: 'Describe changes'
  provider: GitHub
  auth_token:
    secure: tCr7eKazElu1h4Hu0NoAsvW8Aux4cxkMkSpmGuVu4MpFCifawz74aSuFkOxjtSU4
  draft: true
  prerelease: false