skip_tags: false
skip_non_tags: true

image:
  - Visual Studio 2019
  - Ubuntu
  - macos

platform:
  - x86
  - x64

cache:
  - node_modules

init:
  - git config --global core.autocrlf input
  
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019
          platform: x86
    install:
        - ps: Install-Product node 14 x86
        - npm ci
    build_script:
      - npm run make
  -
    matrix:
      only:
        - image: Visual Studio 2019
          platform: x64
    install:
        - ps: Install-Product node 14 x64
        - npm ci
    build_script:
      - npm run make
  -
    matrix:
      only:
        - image: Ubuntu
          platform: x86
      install:
        - nvm install 14
        - npm ci
      build_script:
        - npm run make
  -
    matrix:
      only:
        - image: Ubuntu
          platform: x64
      install:
        - nvm install 14
        - npm ci
      build_script:
        - npm run make
  -
    matrix:
      only:
        - image: macos
          platform: x86
      install:
        - nvm install 14
        - npm ci
      build_script:
        - npm run make
  -
    matrix:
      only:
        - image: macos
          platform: x64
      install:
        - nvm install 14
        - npm ci
      build_script:
        - npm run make

test: false

artifacts:
  - path: out/make/**/*
    name: Worksnake-$env:PLATFORM

#Disabled until I manage to fix this
#deploy:
#  repository: Worksnake/worksnake-releases
#  release: RENAME
#  description: FillIn
#  provider: Github
#  auth_token:
#    secure: 5tEqSzM/9afOkovJUSyOrOGkIjjwZcbvt6di82NYWOaCiX/pJNm0u+OjMaT7yh9v
#  artifact: out/make/**/*
#  draft: true
#  prerelease: false