language: node_js

node_js:
  - '14.15.0'

env:
  global:
    secure: LkXNePnzXXUtKf41SbjP2a37Fj93030ElswQg5JuAyW8ppuIlsouK6RfwVU496DuAV8v9d8GBAx+FBP90Pt5sKxrnZyISdQnMaT+kKxw3Jpra9zYNrEo7Rdnu+LEbS9oNGxvq/QxAvHWSACqVVabAjnwWeSzigjopYtGb3gUHGqvuGs4otU+o0ez5oRksYZF2FN99hy05K9+65wmRwiIwILSYZZmcfrfGyAokefa6Az3auu2RukSZjSwpB7WhZ2CS8xi5UTPSuhgd8onpgEcqJsIgRTfDaHRmCNygPo8HK0fIAnQ8vYnyEf+X7+kcUG4Ljd1rgHsjnwZOV4PeEbGmXme4mUw640SkkU+a6vNuStuoI20ulWaPfRqHApnQQpexZVVXxsWOu+XU8N6kqJ8vQA8JKPtiM+pBu/fN2jVddPd11E50hBX5qDUVBZdbmOEw3qmSvkk9Imnv09LSZCrfQEXH6aG/E6uUsMq7RM/Wffbj1plp1DFKIbioD3Z6gbJ4i8mMoX1lW7IwIIu6e1Uo4zfT2oViExEVAYuUjDgsuZIZwcZShq/vqdCTq6vq9oPjHSbb4+TYfnjn/md3yIkogktuI0oHqqKj0rIgFCV4YcMZ4+QyL88qwo95hINLlpC5YdDOj55EkmmJZD1a+CedqstsA9pklKEGpdgwjT2BMI=

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "14.15.0"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      dist: xenial
      services: docker
      language: generic

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
      export PATH="/tmp/git-lfs:$PATH"
    fi
before_script:
  - git lfs pull

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn dist --linux AppImage --win"
    else
      yarn dist
    fi
    
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  only:
  - master