version: 2.1
orbs:
  node: circleci/node@4.1.0
  windows: circleci/windows@2.4.0
workflows:
  build_linux:
    jobs:
      build:
        machine:
          image: ubuntu-2004
          steps:
            - checkout
            - node/install
            - run: npm run make
  
  build_osx:
    jobs:
      build:
        macos:
          xcode: 11.3.0
        steps:
          - checkout
          - node/install
          - run: npm run make
  
  build_windows:
    jobs:
      build:
        executor: windows/default
        steps:
          - checkout
          - node/install
          - run: npm run make