name: build
on: [push]

jobs:   
  build:
    env:
      GH_TOKEN: ${{ secrets.WORKSNAKE_PERSONAL_TOKEN }}
      ELECTRON_CACHE: $HOME/.cache/electron
      ELECTRON_BUILDER_CACHE: $HOME/.cache/electron-builder

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        arch:
          - 'x64'
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Echo config
        run: echo "Running ${{ matrix.os }} ${{ matrix.arch }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Cache electron and electron-builder
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.cache/electron
            $HOME/.cache/electron-builder
          key: ${{ matrix.os }}-electron

      - name: Install dependecies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: yarn dist