name: Build_Electron

on:
  label:
    types: [created]
    branches:
      - master

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 15.2
    - name: see out directory
      run: ls ./out